### ISSUE TITLE
no function named "

### ISSUE THREAD

**Issue by Sangluisme** [dsilvavinicius/differential_geometry_in_neural_implicits#1]
Hi,
in your code 
https://github.com/dsilvavinicius/differential_geometry_in_neural_implicits/blob/bdd71f599123acc121ce7f5deb9714587bc2be67/main.py#L16
but there is no function name `true_sdf_curvature` in `loss_functions.py`.  Should it be ``mean_curvature_sdf`?
And also here
https://github.com/dsilvavinicius/differential_geometry_in_neural_implicits/blob/bdd71f599123acc121ce7f5deb9714587bc2be67/main.py#L199

Thanks.

**Comment by schardong** [comment]
Hello!

I will look into it and give feedback as soon as possible, OK?

**Comment by Sangluisme** [comment]
> Hello!
> 
> I will look into it and give feedback as soon as possible, OK?

Thanks a lot. 
 I substituted `true_sdf_curvature` with `mean_curvature_sdf`, so far it runs though and results look nice :p

**Comment by schardong** [comment]
> > Hello!
> > I will look into it and give feedback as soon as possible, OK?
> 
> Thanks a lot. I substituted `true_sdf_curvature` with `mean_curvature_sdf`, so far it runs though and results look nice :p

I've checked the commit log, and you are right. In commit 85994b24687277044216e0ce084c8f9112df3e8d we've renamed the `true_sdf_curvature` function to `mean_sdf_curvature`, to make the name clearer, but I forgot to review the import statements. I've committed a new version that fixes the import in `main.py` (a755c0bb5ab0f7f9e12852502cbfb261ccabdb2a).

If you have any questions, please ask!
